src/Entity/Bestelling.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BestellingRepository")
 */
class Bestelling
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $Datum;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gerecht")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Gerecht;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Reservatie")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Reservatie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Factuur", inversedBy="Bestelling")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Factuur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->Datum;
    }

    public function setDatum(\DateTimeInterface $Datum): self
    {
        $this->Datum = $Datum;

        return $this;
    }

    public function getGerecht(): ?Gerecht
    {
        return $this->Gerecht;
    }

    public function setGerecht(?Gerecht $Gerecht): self
    {
        $this->Gerecht = $Gerecht;

        return $this;
    }

    public function getReservatie(): ?Reservatie
    {
        return $this->Reservatie;
    }

    public function setReservatie(?Reservatie $Reservatie): self
    {
        $this->Reservatie = $Reservatie;

        return $this;
    }

    public function getFactuur(): ?Factuur
    {
        return $this->Factuur;
    }

    public function setFactuur(?Factuur $Factuur): self
    {
        $this->Factuur = $Factuur;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getId();
    }
}

src/Entity/Factuur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FactuurRepository")
 */
class Factuur
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Bestelling", mappedBy="Factuur")
     */
    private $Bestelling;

    public function __construct()
    {
        $this->Bestelling = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Bestelling[]
     */
    public function getBestelling(): Collection
    {
        return $this->Bestelling;
    }

    public function addBestelling(Bestelling $bestelling): self
    {
        if (!$this->Bestelling->contains($bestelling)) {
            $this->Bestelling[] = $bestelling;
            $bestelling->setFactuur($this);
        }

        return $this;
    }

    public function removeBestelling(Bestelling $bestelling): self
    {
        if ($this->Bestelling->contains($bestelling)) {
            $this->Bestelling->removeElement($bestelling);
            // set the owning side to null (unless already changed)
            if ($bestelling->getFactuur() === $this) {
                $bestelling->setFactuur(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return strval($this->getId());
    }
}

src/Entity/Gerecht.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GerechtRepository")
 */
class Gerecht
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Naam;

    /**
     * @ORM\Column(type="float")
     */
    private $Prijs;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNaam(): ?string
    {
        return $this->Naam;
    }

    public function setNaam(string $Naam): self
    {
        $this->Naam = $Naam;

        return $this;
    }

    public function getPrijs(): ?float
    {
        return $this->Prijs;
    }

    public function setPrijs(float $Prijs): self
    {
        $this->Prijs = $Prijs;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getNaam();
    }
}

src/Form/FactuurType.php
<?php

namespace App\Form;

use App\Entity\Factuur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FactuurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Bestelling')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Factuur::class,
        ]);
    }
}

src/Controller/FactuurController.php
<?php

namespace App\Controller;

use App\Entity\Bestelling;
use App\Entity\Factuur;
use App\Entity\Gerecht;
use App\Form\FactuurType;
use App\Repository\BestellingRepository;
use App\Repository\FactuurRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/factuur")
 */
class FactuurController extends AbstractController
{
    /**
     * @Route("/", name="factuur_index", methods={"GET"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function index(FactuurRepository $factuurRepository): Response
    {
        return $this->render('factuur/index.html.twig', [
            'factuurs' => $factuurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="factuur_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $factuur = new Factuur();
        $form = $this->createForm(FactuurType::class, $factuur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($factuur);
            $entityManager->flush();

            return $this->redirectToRoute('factuur_index');
        }

        return $this->render('factuur/new.html.twig', [
            'factuur' => $factuur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="factuur_show", methods={"GET"})
     */
    public function show(Factuur $factuur, BestellingRepository $bestellingRepository): Response
    {
        $bestellingen = $factuur->getBestelling();
        $Aantallen = [];
        $Bestellingen = [];

        foreach ($bestellingen as $bestelling) {
            $gerecht = $bestelling->getGerecht();

            if (isset($Aantallen[$gerecht->getId()])) {
                $Aantallen[$gerecht->getId()]["Aantal"]++;
            } else {
                array_push($Bestellingen, $bestelling);
                $Aantallen[$gerecht->getId()] = ["Aantal" => 1];
            }
        }

        return $this->render('factuur/show.html.twig', [
            'factuur'  => $factuur,
            'Bestellingen' => $Bestellingen,
            'Aantallen' => $Aantallen
        ]);
    }

    /**
     * @Route("/{id}/edit", name="factuur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Factuur $factuur): Response
    {
        $form = $this->createForm(FactuurType::class, $factuur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('factuur_index');
        }

        return $this->render('factuur/edit.html.twig', [
            'factuur' => $factuur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="factuur_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Factuur $factuur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$factuur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($factuur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('factuur_index');
    }
}

templates/factuur/_delete_form.html.twig
<form method="post" action="{{ path('factuur_delete', {'id': factuur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ factuur.id) }}">
    <button class="btn d-print-none">Delete</button>
</form>

templates/factuur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/factuur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Factuur{% endblock %}

{% block body %}
    <h1>Edit Factuur</h1>

    {{ include('factuur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('factuur_index') }}">back to list</a>

    {{ include('factuur/_delete_form.html.twig') }}
{% endblock %}

templates/factuur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factuur index{% endblock %}

{% block body %}
    <h1>Factuur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for factuur in factuurs %}
            <tr>
                <td>{{ factuur.id }}</td>
                <td>
                    <a href="{{ path('factuur_show', {'id': factuur.id}) }}">show</a>
                    <a href="{{ path('factuur_edit', {'id': factuur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="2">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('factuur_new') }}">Create new</a>
{% endblock %}

templates/factuur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Factuur{% endblock %}

{% block body %}
    <h1>Create new Factuur</h1>

    {{ include('factuur/_form.html.twig') }}

    <a href="{{ path('factuur_index') }}">back to list</a>
{% endblock %}

templates/factuur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Factuur{% endblock %}

{% block body %}
    <h1>Factuur</h1>

    <table class="table">
        <thead class="thead-dark">
                <tr>
                    <th>Gerecht</th>
                    <th>Prijs (Per stuk)</th>
                    <th>Aantal</th>
                    <th>Prijs</th>
                </tr>
        </thead>
        <tbody>
                {% set Totaal = 0 %}

                {% for Bestelling in Bestellingen %}
                    {% set Aantal = 0 %}

                    {% for bestelling in Aantallen|keys %}
                        {% if bestelling is same as(Bestelling.gerecht.id) %}
                            {% set Aantal = Aantallen[bestelling]["Aantal"] %}
                        {% endif %}
                    {% endfor %}
                    <tr>
                        <td>
                            {{ Bestelling.gerecht }}
                        </td>
                        <td>
                            € {{ Bestelling.gerecht.prijs|number_format(2, ',', '.') }}
                        </td>
                        <td>
                            {{ Aantal }}
                        </td>
                        <td>
                            € {{ (Aantal * Bestelling.gerecht.prijs)|number_format(2, ',', '.') }}
                            {% set Totaal = Totaal + (Aantal * Bestelling.gerecht.prijs) %}
                        </td>
                    </tr>
                {% endfor %}
        </tbody>
        <tfoot>
            <tr class="table-dark">
                <td colspan="2"></td>
                <td class="text-dark">Totaal:</td>
                <td class="text-dark">€ {{ Totaal|number_format(2, ',', '.') }}</td>
            </tr>
        </tfoot>
    </table>

    <button onclick="window.print()" class="btn btn-info d-print-none">Print</button>

    <a href="{{ path('factuur_index') }}" class="d-print-none">back to list</a>

    <a href="{{ path('factuur_edit', {'id': factuur.id}) }}" class="d-print-none">edit</a>

    {{ include('factuur/_delete_form.html.twig') }}
{% endblock %}